Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -88,7 +88,7 @@ jobs:
     - &build-and-push-next
       stage: Build & Publish 'next'
       name: Build & Publish image on amd64 
-      if: type = push AND branch = test-release
+      if: type = push AND branch = test123
       arch: amd64
       script: 
       - |
@@ -106,7 +106,7 @@ jobs:
       name: Build & Publish image on s390x
 
     - stage: Publish multiarch image with 'next' tag
-      if: type = push AND branch = test-release
+      if: type = push AND branch = test123
       name: Publish multiarch image with next tag
       script: .travis/publish_multiarch.sh
 
@@ -200,15 +200,16 @@ jobs:
        - | 
          set -e
          .travis/publish_multiarch.sh
-      after_success:
-       - |
-         set -e
-         echo "{\"text\":\":white_check_mark: Che Theia ${TAG} has been released: https://quay.io/eclipse/che-theia-dev:${TAG} https://quay.io/eclipse/che-theia:${TAG} https://quay.io/eclipse/che-theia-endpoint-runtime-binary:${TAG} https://quay.io/eclipse/che-theia-vsix-installer:${TAG}\"}" > mattermost.json
-         cat mattermost.json
-         curl -i -X POST -H 'Content-Type: application/json' -d @mattermost.json $MATTERMOST_WEBHOOK_URL
-      after_failure:
-       - |
-         set -e
-         echo "{\"text\":\":no_entry_sign: Che Theia ${TAG} release has failed: https://github.com/eclipse-che/che-theia/actions/workflows/release.yml\"}" > mattermost.json
-         cat mattermost.json
-         curl -i -X POST -H 'Content-Type: application/json' -d @mattermost.json $MATTERMOST_WEBHOOK_URL
+      
+after_success:
+ - |
+   set -e
+   echo "{\"text\":\":white_check_mark: Che Theia ${TAG} has been released: https://quay.io/eclipse/che-theia-dev:${TAG} https://quay.io/eclipse/che-theia:${TAG} https://quay.io/eclipse/che-theia-endpoint-runtime-binary:${TAG} https://quay.io/eclipse/che-theia-vsix-installer:${TAG}\"}" > mattermost.json
+   cat mattermost.json
+   curl -i -X POST -H 'Content-Type: application/json' -d @mattermost.json $MATTERMOST_WEBHOOK_URL
+after_failure:
+ - |
+   set -e
+   echo "{\"text\":\":no_entry_sign: Che Theia ${TAG} release has failed: https://github.com/eclipse-che/che-theia/actions/workflows/release.yml\"}" > mattermost.json
+   cat mattermost.json
+   curl -i -X POST -H 'Content-Type: application/json' -d @mattermost.json $MATTERMOST_WEBHOOK_URL
